services:
  credential_vault_pg:
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: credential_vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
      PGTZ: "UTC"
    volumes:
      - credential_vault_pg_data:/var/lib/postgresql/data
      - ../../credential_vault/pg_interface/migrate/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql

  credential_vault:
    build:
      context: ../../
      dockerfile: credential_vault/docker/credential_vault.Dockerfile
    ports:
      # You can change the port number to your desired port number
      - "4201:4201"
    platform: linux/amd64
    restart: unless-stopped
    environment:
      # You can change the port number to your desired port number
      PORT: "4201"
      DB_HOST: "credential_vault_pg"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "credential_vault"
      DB_SSL: "false"

    depends_on:
      - credential_vault_pg

volumes:
  credential_vault_pg_data:
