[package]
name = "credential-vault-migrate"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "migrate"
path = "src/main.rs"

[dependencies]
credential-vault-pg-interface = { path = ".." }
tokio = { version = "1.0", features = ["full"] }